# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.api.featuretypes_api import FeaturetypesApi  # noqa: E501
from geoserver.rest import ApiException


class TestFeaturetypesApi(unittest.TestCase):
    """FeaturetypesApi unit test stubs"""

    def setUp(self):
        self.api = FeaturetypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_feature_type(self):
        """Test case for create_feature_type

        """
        pass

    def test_create_feature_type_on_store(self):
        """Test case for create_feature_type_on_store

        """
        pass

    def test_delete_feature_type(self):
        """Test case for delete_feature_type

        """
        pass

    def test_delete_feature_type_by_store(self):
        """Test case for delete_feature_type_by_store

        """
        pass

    def test_get_feature_type(self):
        """Test case for get_feature_type

        """
        pass

    def test_get_feature_type_by_default_store(self):
        """Test case for get_feature_type_by_default_store

        """
        pass

    def test_get_feature_types_by_store(self):
        """Test case for get_feature_types_by_store

        """
        pass

    def test_get_feature_types_by_workspace(self):
        """Test case for get_feature_types_by_workspace

        """
        pass

    def test_modify_feature_type(self):
        """Test case for modify_feature_type

        """
        pass

    def test_modify_feature_type_by_store(self):
        """Test case for modify_feature_type_by_store

        """
        pass


if __name__ == '__main__':
    unittest.main()
