# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.models.connection_parameter_entry import ConnectionParameterEntry  # noqa: E501
from geoserver.rest import ApiException


class TestConnectionParameterEntry(unittest.TestCase):
    """ConnectionParameterEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionParameterEntry(self):
        """Test ConnectionParameterEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = geoserver.models.connection_parameter_entry.ConnectionParameterEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
