# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.api.settings_api import SettingsApi  # noqa: E501
from geoserver.rest import ApiException


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_local_settings(self):
        """Test case for create_local_settings

        Create workspace-specific settings  # noqa: E501
        """
        pass

    def test_get_global_contact_info(self):
        """Test case for get_global_contact_info

        Get the global contact information  # noqa: E501
        """
        pass

    def test_get_local_settings(self):
        """Test case for get_local_settings

        Get workspace-specific settings  # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

        Get geoserver global settings  # noqa: E501
        """
        pass

    def test_update_global_contact_info(self):
        """Test case for update_global_contact_info

        Update contact settings  # noqa: E501
        """
        pass

    def test_update_local_settings(self):
        """Test case for update_local_settings

        Update workspace-specific settings  # noqa: E501
        """
        pass

    def test_update_settings(self):
        """Test case for update_settings

        Update the global configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
