# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.api.ows_services_api import OwsServicesApi  # noqa: E501
from geoserver.rest import ApiException


class TestOwsServicesApi(unittest.TestCase):
    """OwsServicesApi unit test stubs"""

    def setUp(self):
        self.api = OwsServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_local_wcs_settings(self):
        """Test case for delete_local_wcs_settings

        """
        pass

    def test_delete_local_wfs_settings(self):
        """Test case for delete_local_wfs_settings

        """
        pass

    def test_delete_local_wms_settings(self):
        """Test case for delete_local_wms_settings

        """
        pass

    def test_delete_local_wmts_settings(self):
        """Test case for delete_local_wmts_settings

        """
        pass

    def test_get_local_wcs_settings(self):
        """Test case for get_local_wcs_settings

        """
        pass

    def test_get_local_wfs_settings(self):
        """Test case for get_local_wfs_settings

        """
        pass

    def test_get_local_wms_settings(self):
        """Test case for get_local_wms_settings

        """
        pass

    def test_get_local_wmts_settings(self):
        """Test case for get_local_wmts_settings

        """
        pass

    def test_get_wcs_settings(self):
        """Test case for get_wcs_settings

        """
        pass

    def test_get_wfs_settings(self):
        """Test case for get_wfs_settings

        """
        pass

    def test_get_wms_settings(self):
        """Test case for get_wms_settings

        """
        pass

    def test_get_wmts_settings(self):
        """Test case for get_wmts_settings

        """
        pass

    def test_update_local_wcs_settings(self):
        """Test case for update_local_wcs_settings

        """
        pass

    def test_update_local_wfs_settings(self):
        """Test case for update_local_wfs_settings

        """
        pass

    def test_update_local_wms_settings(self):
        """Test case for update_local_wms_settings

        """
        pass

    def test_update_local_wmts_settings(self):
        """Test case for update_local_wmts_settings

        """
        pass

    def test_update_wcs_settings(self):
        """Test case for update_wcs_settings

        """
        pass

    def test_update_wfs_settings(self):
        """Test case for update_wfs_settings

        """
        pass

    def test_update_wms_settings(self):
        """Test case for update_wms_settings

        """
        pass

    def test_update_wmts_settings(self):
        """Test case for update_wmts_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
