# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.api.default_api import DefaultApi  # noqa: E501
from geoserver.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_workspace_settings(self):
        """Test case for delete_workspace_settings

        """
        pass

    def test_fake_op(self):
        """Test case for fake_op

        """
        pass


if __name__ == '__main__':
    unittest.main()
