# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.models.attribute_type_info import AttributeTypeInfo  # noqa: E501
from geoserver.rest import ApiException


class TestAttributeTypeInfo(unittest.TestCase):
    """AttributeTypeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeTypeInfo(self):
        """Test AttributeTypeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = geoserver.models.attribute_type_info.AttributeTypeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
