# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.api.namespaces_api import NamespacesApi  # noqa: E501
from geoserver.rest import ApiException


class TestNamespacesApi(unittest.TestCase):
    """NamespacesApi unit test stubs"""

    def setUp(self):
        self.api = NamespacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_namespace(self):
        """Test case for add_namespace

        Add a new namespace to GeoServer  # noqa: E501
        """
        pass

    def test_delete_namespace(self):
        """Test case for delete_namespace

        Delete a namespace  # noqa: E501
        """
        pass

    def test_get_namespace(self):
        """Test case for get_namespace

        Retrieve a namespace  # noqa: E501
        """
        pass

    def test_get_namespaces(self):
        """Test case for get_namespaces

        Get a list of namespaces  # noqa: E501
        """
        pass

    def test_modify_namespace(self):
        """Test case for modify_namespace

        Update a namespace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
