# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import geoserver
from geoserver.api.datastores_api import DatastoresApi  # noqa: E501
from geoserver.rest import ApiException


class TestDatastoresApi(unittest.TestCase):
    """DatastoresApi unit test stubs"""

    def setUp(self):
        self.api = DatastoresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_datastore(self):
        """Test case for create_datastore

        Create a new data store  # noqa: E501
        """
        pass

    def test_delete_datastore(self):
        """Test case for delete_datastore

        Delete data store  # noqa: E501
        """
        pass

    def test_get_data_store(self):
        """Test case for get_data_store

        Retrieve a particular data store from a workspace  # noqa: E501
        """
        pass

    def test_get_datastores(self):
        """Test case for get_datastores

        Get a list of data stores  # noqa: E501
        """
        pass

    def test_modify_data_store(self):
        """Test case for modify_data_store

        Modify a data store.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
