# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComponentVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'build_timestamp': 'str',
        'git_revision': 'str',
        'version': 'str'
    }

    attribute_map = {
        'name': '@name',
        'build_timestamp': 'Build-Timestamp',
        'git_revision': 'Git-Revision',
        'version': 'Version'
    }

    def __init__(self, name=None, build_timestamp=None, git_revision=None, version=None):  # noqa: E501
        """ComponentVersion - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._build_timestamp = None
        self._git_revision = None
        self._version = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if build_timestamp is not None:
            self.build_timestamp = build_timestamp
        if git_revision is not None:
            self.git_revision = git_revision
        if version is not None:
            self.version = version

    @property
    def name(self):
        """Gets the name of this ComponentVersion.  # noqa: E501


        :return: The name of this ComponentVersion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ComponentVersion.


        :param name: The name of this ComponentVersion.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def build_timestamp(self):
        """Gets the build_timestamp of this ComponentVersion.  # noqa: E501


        :return: The build_timestamp of this ComponentVersion.  # noqa: E501
        :rtype: str
        """
        return self._build_timestamp

    @build_timestamp.setter
    def build_timestamp(self, build_timestamp):
        """Sets the build_timestamp of this ComponentVersion.


        :param build_timestamp: The build_timestamp of this ComponentVersion.  # noqa: E501
        :type: str
        """

        self._build_timestamp = build_timestamp

    @property
    def git_revision(self):
        """Gets the git_revision of this ComponentVersion.  # noqa: E501


        :return: The git_revision of this ComponentVersion.  # noqa: E501
        :rtype: str
        """
        return self._git_revision

    @git_revision.setter
    def git_revision(self, git_revision):
        """Sets the git_revision of this ComponentVersion.


        :param git_revision: The git_revision of this ComponentVersion.  # noqa: E501
        :type: str
        """

        self._git_revision = git_revision

    @property
    def version(self):
        """Gets the version of this ComponentVersion.  # noqa: E501


        :return: The version of this ComponentVersion.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ComponentVersion.


        :param version: The version of this ComponentVersion.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComponentVersion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComponentVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
