# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GeoServerInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'update_sequence': 'int',
        'use_headers_proxy_url': 'bool',
        'settings': 'SettingsInfo'
    }

    attribute_map = {
        'update_sequence': 'updateSequence',
        'use_headers_proxy_url': 'useHeadersProxyURL',
        'settings': 'settings'
    }

    def __init__(self, update_sequence=None, use_headers_proxy_url=None, settings=None):  # noqa: E501
        """GeoServerInfo - a model defined in Swagger"""  # noqa: E501
        self._update_sequence = None
        self._use_headers_proxy_url = None
        self._settings = None
        self.discriminator = None
        if update_sequence is not None:
            self.update_sequence = update_sequence
        if use_headers_proxy_url is not None:
            self.use_headers_proxy_url = use_headers_proxy_url
        if settings is not None:
            self.settings = settings

    @property
    def update_sequence(self):
        """Gets the update_sequence of this GeoServerInfo.  # noqa: E501

        The update sequence. This value is used by various ogc services to track changes to a capabilities document.  # noqa: E501

        :return: The update_sequence of this GeoServerInfo.  # noqa: E501
        :rtype: int
        """
        return self._update_sequence

    @update_sequence.setter
    def update_sequence(self, update_sequence):
        """Sets the update_sequence of this GeoServerInfo.

        The update sequence. This value is used by various ogc services to track changes to a capabilities document.  # noqa: E501

        :param update_sequence: The update_sequence of this GeoServerInfo.  # noqa: E501
        :type: int
        """

        self._update_sequence = update_sequence

    @property
    def use_headers_proxy_url(self):
        """Gets the use_headers_proxy_url of this GeoServerInfo.  # noqa: E501

        The flag to use request headers for the proxy URL  # noqa: E501

        :return: The use_headers_proxy_url of this GeoServerInfo.  # noqa: E501
        :rtype: bool
        """
        return self._use_headers_proxy_url

    @use_headers_proxy_url.setter
    def use_headers_proxy_url(self, use_headers_proxy_url):
        """Sets the use_headers_proxy_url of this GeoServerInfo.

        The flag to use request headers for the proxy URL  # noqa: E501

        :param use_headers_proxy_url: The use_headers_proxy_url of this GeoServerInfo.  # noqa: E501
        :type: bool
        """

        self._use_headers_proxy_url = use_headers_proxy_url

    @property
    def settings(self):
        """Gets the settings of this GeoServerInfo.  # noqa: E501


        :return: The settings of this GeoServerInfo.  # noqa: E501
        :rtype: SettingsInfo
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this GeoServerInfo.


        :param settings: The settings of this GeoServerInfo.  # noqa: E501
        :type: SettingsInfo
        """

        self._settings = settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeoServerInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeoServerInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
