# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GridInfoResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dimension': 'str',
        'crs': 'str',
        'range': 'object',
        'transform': 'object'
    }

    attribute_map = {
        'dimension': '@dimension',
        'crs': 'crs',
        'range': 'range',
        'transform': 'transform'
    }

    def __init__(self, dimension=None, crs=None, range=None, transform=None):  # noqa: E501
        """GridInfoResponse - a model defined in Swagger"""  # noqa: E501
        self._dimension = None
        self._crs = None
        self._range = None
        self._transform = None
        self.discriminator = None
        if dimension is not None:
            self.dimension = dimension
        if crs is not None:
            self.crs = crs
        if range is not None:
            self.range = range
        if transform is not None:
            self.transform = transform

    @property
    def dimension(self):
        """Gets the dimension of this GridInfoResponse.  # noqa: E501


        :return: The dimension of this GridInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._dimension

    @dimension.setter
    def dimension(self, dimension):
        """Sets the dimension of this GridInfoResponse.


        :param dimension: The dimension of this GridInfoResponse.  # noqa: E501
        :type: str
        """

        self._dimension = dimension

    @property
    def crs(self):
        """Gets the crs of this GridInfoResponse.  # noqa: E501


        :return: The crs of this GridInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._crs

    @crs.setter
    def crs(self, crs):
        """Sets the crs of this GridInfoResponse.


        :param crs: The crs of this GridInfoResponse.  # noqa: E501
        :type: str
        """

        self._crs = crs

    @property
    def range(self):
        """Gets the range of this GridInfoResponse.  # noqa: E501


        :return: The range of this GridInfoResponse.  # noqa: E501
        :rtype: object
        """
        return self._range

    @range.setter
    def range(self, range):
        """Sets the range of this GridInfoResponse.


        :param range: The range of this GridInfoResponse.  # noqa: E501
        :type: object
        """

        self._range = range

    @property
    def transform(self):
        """Gets the transform of this GridInfoResponse.  # noqa: E501


        :return: The transform of this GridInfoResponse.  # noqa: E501
        :rtype: object
        """
        return self._transform

    @transform.setter
    def transform(self, transform):
        """Sets the transform of this GridInfoResponse.


        :param transform: The transform of this GridInfoResponse.  # noqa: E501
        :type: object
        """

        self._transform = transform

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GridInfoResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GridInfoResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
