# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LegendInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'width': 'int',
        'height': 'int',
        'format': 'str',
        'online_resource': 'str'
    }

    attribute_map = {
        'width': 'width',
        'height': 'height',
        'format': 'format',
        'online_resource': 'onlineResource'
    }

    def __init__(self, width=None, height=None, format=None, online_resource=None):  # noqa: E501
        """LegendInfo - a model defined in Swagger"""  # noqa: E501
        self._width = None
        self._height = None
        self._format = None
        self._online_resource = None
        self.discriminator = None
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if format is not None:
            self.format = format
        if online_resource is not None:
            self.online_resource = online_resource

    @property
    def width(self):
        """Gets the width of this LegendInfo.  # noqa: E501

        Width of the legend  # noqa: E501

        :return: The width of this LegendInfo.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this LegendInfo.

        Width of the legend  # noqa: E501

        :param width: The width of this LegendInfo.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this LegendInfo.  # noqa: E501

        Height of the legend  # noqa: E501

        :return: The height of this LegendInfo.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this LegendInfo.

        Height of the legend  # noqa: E501

        :param height: The height of this LegendInfo.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def format(self):
        """Gets the format of this LegendInfo.  # noqa: E501

        Format of the legend.  # noqa: E501

        :return: The format of this LegendInfo.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this LegendInfo.

        Format of the legend.  # noqa: E501

        :param format: The format of this LegendInfo.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def online_resource(self):
        """Gets the online_resource of this LegendInfo.  # noqa: E501

        Online resource of the legend.  # noqa: E501

        :return: The online_resource of this LegendInfo.  # noqa: E501
        :rtype: str
        """
        return self._online_resource

    @online_resource.setter
    def online_resource(self, online_resource):
        """Sets the online_resource of this LegendInfo.

        Online resource of the legend.  # noqa: E501

        :param online_resource: The online_resource of this LegendInfo.  # noqa: E501
        :type: str
        """

        self._online_resource = online_resource

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LegendInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LegendInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
