# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetadataLinkInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'about': 'str',
        'content': 'str',
        'metadata_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'about': 'about',
        'content': 'content',
        'metadata_type': 'metadataType'
    }

    def __init__(self, id=None, about=None, content=None, metadata_type=None):  # noqa: E501
        """MetadataLinkInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._about = None
        self._content = None
        self._metadata_type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if about is not None:
            self.about = about
        if content is not None:
            self.content = content
        if metadata_type is not None:
            self.metadata_type = metadata_type

    @property
    def id(self):
        """Gets the id of this MetadataLinkInfo.  # noqa: E501

        Metadata identifier  # noqa: E501

        :return: The id of this MetadataLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MetadataLinkInfo.

        Metadata identifier  # noqa: E501

        :param id: The id of this MetadataLinkInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def about(self):
        """Gets the about of this MetadataLinkInfo.  # noqa: E501


        :return: The about of this MetadataLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._about

    @about.setter
    def about(self, about):
        """Sets the about of this MetadataLinkInfo.


        :param about: The about of this MetadataLinkInfo.  # noqa: E501
        :type: str
        """

        self._about = about

    @property
    def content(self):
        """Gets the content of this MetadataLinkInfo.  # noqa: E501


        :return: The content of this MetadataLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this MetadataLinkInfo.


        :param content: The content of this MetadataLinkInfo.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def metadata_type(self):
        """Gets the metadata_type of this MetadataLinkInfo.  # noqa: E501


        :return: The metadata_type of this MetadataLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._metadata_type

    @metadata_type.setter
    def metadata_type(self, metadata_type):
        """Sets the metadata_type of this MetadataLinkInfo.


        :param metadata_type: The metadata_type of this MetadataLinkInfo.  # noqa: E501
        :type: str
        """

        self._metadata_type = metadata_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetadataLinkInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataLinkInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
