# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResourceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'native_name': 'str',
        'alias': 'list[str]',
        'namespace': 'NamedLink',
        'title': 'str',
        'abstract': 'str',
        'description': 'str',
        'enabled': 'bool',
        'advertised': 'bool',
        'keywords': 'object',
        'native_bounding_box': 'EnvelopeResponse',
        'lat_lon_bounding_box': 'EnvelopeResponse',
        'srs': 'str',
        'native_crs': 'CRSResponse',
        'projection_policy': 'CatalogYamlcomponentsschemasProjectionPolicy',
        'store': 'NamedLink',
        'service_configuration': 'bool',
        'disabled_services': 'StringArrayResponse'
    }

    attribute_map = {
        'name': 'name',
        'native_name': 'nativeName',
        'alias': 'alias',
        'namespace': 'namespace',
        'title': 'title',
        'abstract': 'abstract',
        'description': 'description',
        'enabled': 'enabled',
        'advertised': 'advertised',
        'keywords': 'keywords',
        'native_bounding_box': 'nativeBoundingBox',
        'lat_lon_bounding_box': 'latLonBoundingBox',
        'srs': 'srs',
        'native_crs': 'nativeCRS',
        'projection_policy': 'projectionPolicy',
        'store': 'store',
        'service_configuration': 'serviceConfiguration',
        'disabled_services': 'disabledServices'
    }

    def __init__(self, name=None, native_name=None, alias=None, namespace=None, title=None, abstract=None, description=None, enabled=None, advertised=None, keywords=None, native_bounding_box=None, lat_lon_bounding_box=None, srs=None, native_crs=None, projection_policy=None, store=None, service_configuration=None, disabled_services=None):  # noqa: E501
        """ResourceResponse - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._native_name = None
        self._alias = None
        self._namespace = None
        self._title = None
        self._abstract = None
        self._description = None
        self._enabled = None
        self._advertised = None
        self._keywords = None
        self._native_bounding_box = None
        self._lat_lon_bounding_box = None
        self._srs = None
        self._native_crs = None
        self._projection_policy = None
        self._store = None
        self._service_configuration = None
        self._disabled_services = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if native_name is not None:
            self.native_name = native_name
        if alias is not None:
            self.alias = alias
        if namespace is not None:
            self.namespace = namespace
        if title is not None:
            self.title = title
        if abstract is not None:
            self.abstract = abstract
        if description is not None:
            self.description = description
        if enabled is not None:
            self.enabled = enabled
        if advertised is not None:
            self.advertised = advertised
        if keywords is not None:
            self.keywords = keywords
        if native_bounding_box is not None:
            self.native_bounding_box = native_bounding_box
        if lat_lon_bounding_box is not None:
            self.lat_lon_bounding_box = lat_lon_bounding_box
        if srs is not None:
            self.srs = srs
        if native_crs is not None:
            self.native_crs = native_crs
        if projection_policy is not None:
            self.projection_policy = projection_policy
        if store is not None:
            self.store = store
        if service_configuration is not None:
            self.service_configuration = service_configuration
        if disabled_services is not None:
            self.disabled_services = disabled_services

    @property
    def name(self):
        """Gets the name of this ResourceResponse.  # noqa: E501


        :return: The name of this ResourceResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ResourceResponse.


        :param name: The name of this ResourceResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def native_name(self):
        """Gets the native_name of this ResourceResponse.  # noqa: E501


        :return: The native_name of this ResourceResponse.  # noqa: E501
        :rtype: str
        """
        return self._native_name

    @native_name.setter
    def native_name(self, native_name):
        """Sets the native_name of this ResourceResponse.


        :param native_name: The native_name of this ResourceResponse.  # noqa: E501
        :type: str
        """

        self._native_name = native_name

    @property
    def alias(self):
        """Gets the alias of this ResourceResponse.  # noqa: E501


        :return: The alias of this ResourceResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this ResourceResponse.


        :param alias: The alias of this ResourceResponse.  # noqa: E501
        :type: list[str]
        """

        self._alias = alias

    @property
    def namespace(self):
        """Gets the namespace of this ResourceResponse.  # noqa: E501


        :return: The namespace of this ResourceResponse.  # noqa: E501
        :rtype: NamedLink
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this ResourceResponse.


        :param namespace: The namespace of this ResourceResponse.  # noqa: E501
        :type: NamedLink
        """

        self._namespace = namespace

    @property
    def title(self):
        """Gets the title of this ResourceResponse.  # noqa: E501


        :return: The title of this ResourceResponse.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ResourceResponse.


        :param title: The title of this ResourceResponse.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def abstract(self):
        """Gets the abstract of this ResourceResponse.  # noqa: E501


        :return: The abstract of this ResourceResponse.  # noqa: E501
        :rtype: str
        """
        return self._abstract

    @abstract.setter
    def abstract(self, abstract):
        """Sets the abstract of this ResourceResponse.


        :param abstract: The abstract of this ResourceResponse.  # noqa: E501
        :type: str
        """

        self._abstract = abstract

    @property
    def description(self):
        """Gets the description of this ResourceResponse.  # noqa: E501


        :return: The description of this ResourceResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ResourceResponse.


        :param description: The description of this ResourceResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def enabled(self):
        """Gets the enabled of this ResourceResponse.  # noqa: E501


        :return: The enabled of this ResourceResponse.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ResourceResponse.


        :param enabled: The enabled of this ResourceResponse.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def advertised(self):
        """Gets the advertised of this ResourceResponse.  # noqa: E501


        :return: The advertised of this ResourceResponse.  # noqa: E501
        :rtype: bool
        """
        return self._advertised

    @advertised.setter
    def advertised(self, advertised):
        """Sets the advertised of this ResourceResponse.


        :param advertised: The advertised of this ResourceResponse.  # noqa: E501
        :type: bool
        """

        self._advertised = advertised

    @property
    def keywords(self):
        """Gets the keywords of this ResourceResponse.  # noqa: E501


        :return: The keywords of this ResourceResponse.  # noqa: E501
        :rtype: object
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this ResourceResponse.


        :param keywords: The keywords of this ResourceResponse.  # noqa: E501
        :type: object
        """

        self._keywords = keywords

    @property
    def native_bounding_box(self):
        """Gets the native_bounding_box of this ResourceResponse.  # noqa: E501


        :return: The native_bounding_box of this ResourceResponse.  # noqa: E501
        :rtype: EnvelopeResponse
        """
        return self._native_bounding_box

    @native_bounding_box.setter
    def native_bounding_box(self, native_bounding_box):
        """Sets the native_bounding_box of this ResourceResponse.


        :param native_bounding_box: The native_bounding_box of this ResourceResponse.  # noqa: E501
        :type: EnvelopeResponse
        """

        self._native_bounding_box = native_bounding_box

    @property
    def lat_lon_bounding_box(self):
        """Gets the lat_lon_bounding_box of this ResourceResponse.  # noqa: E501


        :return: The lat_lon_bounding_box of this ResourceResponse.  # noqa: E501
        :rtype: EnvelopeResponse
        """
        return self._lat_lon_bounding_box

    @lat_lon_bounding_box.setter
    def lat_lon_bounding_box(self, lat_lon_bounding_box):
        """Sets the lat_lon_bounding_box of this ResourceResponse.


        :param lat_lon_bounding_box: The lat_lon_bounding_box of this ResourceResponse.  # noqa: E501
        :type: EnvelopeResponse
        """

        self._lat_lon_bounding_box = lat_lon_bounding_box

    @property
    def srs(self):
        """Gets the srs of this ResourceResponse.  # noqa: E501


        :return: The srs of this ResourceResponse.  # noqa: E501
        :rtype: str
        """
        return self._srs

    @srs.setter
    def srs(self, srs):
        """Sets the srs of this ResourceResponse.


        :param srs: The srs of this ResourceResponse.  # noqa: E501
        :type: str
        """

        self._srs = srs

    @property
    def native_crs(self):
        """Gets the native_crs of this ResourceResponse.  # noqa: E501


        :return: The native_crs of this ResourceResponse.  # noqa: E501
        :rtype: CRSResponse
        """
        return self._native_crs

    @native_crs.setter
    def native_crs(self, native_crs):
        """Sets the native_crs of this ResourceResponse.


        :param native_crs: The native_crs of this ResourceResponse.  # noqa: E501
        :type: CRSResponse
        """

        self._native_crs = native_crs

    @property
    def projection_policy(self):
        """Gets the projection_policy of this ResourceResponse.  # noqa: E501


        :return: The projection_policy of this ResourceResponse.  # noqa: E501
        :rtype: CatalogYamlcomponentsschemasProjectionPolicy
        """
        return self._projection_policy

    @projection_policy.setter
    def projection_policy(self, projection_policy):
        """Sets the projection_policy of this ResourceResponse.


        :param projection_policy: The projection_policy of this ResourceResponse.  # noqa: E501
        :type: CatalogYamlcomponentsschemasProjectionPolicy
        """

        self._projection_policy = projection_policy

    @property
    def store(self):
        """Gets the store of this ResourceResponse.  # noqa: E501


        :return: The store of this ResourceResponse.  # noqa: E501
        :rtype: NamedLink
        """
        return self._store

    @store.setter
    def store(self, store):
        """Sets the store of this ResourceResponse.


        :param store: The store of this ResourceResponse.  # noqa: E501
        :type: NamedLink
        """

        self._store = store

    @property
    def service_configuration(self):
        """Gets the service_configuration of this ResourceResponse.  # noqa: E501


        :return: The service_configuration of this ResourceResponse.  # noqa: E501
        :rtype: bool
        """
        return self._service_configuration

    @service_configuration.setter
    def service_configuration(self, service_configuration):
        """Sets the service_configuration of this ResourceResponse.


        :param service_configuration: The service_configuration of this ResourceResponse.  # noqa: E501
        :type: bool
        """

        self._service_configuration = service_configuration

    @property
    def disabled_services(self):
        """Gets the disabled_services of this ResourceResponse.  # noqa: E501


        :return: The disabled_services of this ResourceResponse.  # noqa: E501
        :rtype: StringArrayResponse
        """
        return self._disabled_services

    @disabled_services.setter
    def disabled_services(self, disabled_services):
        """Sets the disabled_services of this ResourceResponse.


        :param disabled_services: The disabled_services of this ResourceResponse.  # noqa: E501
        :type: StringArrayResponse
        """

        self._disabled_services = disabled_services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
