[tool.poetry]
name = "tools"
version = "0.1.0"
description = ""
authors = ["Andrea Borghi <andrea.borghi@camptocamp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
